### ISSUE TITLE
database is not beeing updated with values

### ISSUE THREAD

**Issue by polpas** [munzli/koubachi-goserver#2]
I followed your tutorial everything fine koubachi config.yml at correct destination with format as example.

database when start docker is created without errors.

I've been 3 days with project running and have no values in charts. the information from the yaml is not showed for examle the name of the koubachi in the charts as a data information.

I'm sending you the yml of my koubachi so you can see if any issues in the structur
[config.txt](https://github.com/munzli/koubachi-goserver/files/7892503/config.txt)
e

**Comment by polpas** [comment]
Im sending you as attachment a preview of my charts
<img width="899" alt="Captura de ecrã 2022-01-18, às 21 36 07" src="https://user-images.githubusercontent.com/14005842/150022627-a1f05439-186c-4804-b5a9-81cc882e7ada.png">

**Comment by polpas** [comment]
I'm sending you also a preview of the communication between the koubachi and the server POST and request webpage
<img width="1548" alt="Captura de ecrã 2022-01-18, às 21 38 31" src="https://user-images.githubusercontent.com/14005842/150022954-094846c2-1f20-49ee-8a73-adf97eb262b1.png">

**Comment by munzli** [comment]
according to your logs, readings have been received with a POST request.
is the `./readings/koubachi.db` sqlite db really empty?

the charts should use GET requests to receive values, kinda like this:
```[GIN] 2022/01/13 - 15:28:55 | 200 |  2.973609868s |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/soil_moisture
[GIN] 2022/01/13 - 15:28:55 | 200 |  162.702526ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/rssi
[GIN] 2022/01/13 - 15:28:56 | 200 |  111.866576ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/temperature
[GIN] 2022/01/13 - 15:28:56 | 200 |   58.356173ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/soil_temperature
[GIN] 2022/01/13 - 15:28:57 | 200 |  4.989018642s |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/battery_voltage
[GIN] 2022/01/13 - 15:28:57 | 200 |  108.747552ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/light
```

if you run the docker image without `-v` or `--volume` for the readings you will always lose the database with every container restart.
also make sure your port is exposed using `-p`.

**Comment by polpas** [comment]
My database only have the name of the tables no more data. Regarding the mount -v and expose of port -p it’s done as described in tutorial. Should the database have more info? I’m sending you the database in attachment so you can check if there is any issue

> No dia 19/01/2022, às 17:00, munzli ***@***.***> escreveu:
> 
> ﻿
> according to your logs, readings have been received with a POST request.
> is the ./readings/koubachi.db sqlite db really empty?
> 
> the charts should use GET requests to receive values, kinda like this:
> 
> [GIN] 2022/01/13 - 15:28:55 | 200 |  162.702526ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/rssi
> [GIN] 2022/01/13 - 15:28:56 | 200 |  111.866576ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/temperature
> [GIN] 2022/01/13 - 15:28:56 | 200 |   58.356173ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/soil_temperature
> [GIN] 2022/01/13 - 15:28:57 | 200 |  4.989018642s |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/battery_voltage
> [GIN] 2022/01/13 - 15:28:57 | 200 |  108.747552ms |   192.168.1.100 | GET      /v1/smart_devices/0006666f77bb/light
> if you run the docker image without -v or --volume for the readings you will always lose the database with every container restart.
> also make sure your port is exposed using -p.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.
[koubachi.db.zip](https://github.com/munzli/koubachi-goserver/files/7900135/koubachi.db.zip)

**Comment by polpas** [comment]
Hi, I added to the table sensors rssi, temperature, soil_temperature, battery_voltage, light. Im sending you the log of the latest communications. the table regarding the values is still empty.
<img width="1565" alt="Captura de ecrã 2022-01-19, às 23 24 33" src="https://user-images.githubusercontent.com/14005842/150234540-7b71f9d1-cf36-4baa-8688-e2f604e58de4.png">

**Comment by munzli** [comment]
images of logs aren't really helpful. could you check and see for errors using `docker logs`.
i.E. `docker logs $(docker ps -q --filter publish=8005 --filter volume=/app/readings)`

`docker ps -q --filter publish=8005 --filter volume=/app/readings` should return the correct container ID if the port and volume are correct.

**Comment by polpas** [comment]
It return the correct container id

CONTAINER ID   IMAGE               COMMAND                  CREATED        STATUS       PORTS                    NAMES
4afcb31af261   koubachi-goserver   "dumb-init -- koubac…"   42 hours ago   Up 4 hours   0.0.0.0:8005->8005/tcp   koubachizinho

If I run:
> docker ps -q --filter publish=8005 --filter volume=/app/readings should return the correct container ID if the port and volume are correct.
> 
> I get the correct ID

May you please tell me something:

- When I initialize koubachi with wi-fi and server ip should the command put populate the database with the data from the koubachi?

- I get no data filled when I put the config.yml my database is not automatically filled with macaddress and sensors types.
 
Is there any way to flash the koubachi sensor? Pressing the button of koubachi for 20 seconds until get red light get the factory definitions or should I press again after rede light to confirm?

**Comment by polpas** [comment]
When I config koubachi the first communication with the server is 

PUT      /v1/smart_devices/000666806f61?locale=en

Is this command well performed?

**Comment by munzli** [comment]
could you please show the logs using `docker logs`

**Comment by polpas** [comment]
Hi,

As requested the docker logs “container” is:

[GIN] 2022/01/20 - 22:09:45 | 201 |     176.184µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/20 - 22:09:45 | 200 |     151.101µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/config?locale=en
[GIN] 2022/01/20 - 22:10:21 | 200 |   15.498924ms |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/20 - 22:10:21 | 200 |     385.496µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/soil_moisture
[GIN] 2022/01/20 - 22:10:21 | 200 |     662.796µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/rssi
[GIN] 2022/01/20 - 22:10:21 | 200 |    1.274502ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/temperature
[GIN] 2022/01/20 - 22:10:21 | 200 |     733.494µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/battery_voltage
[GIN] 2022/01/20 - 22:10:21 | 200 |     600.871µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/light
[GIN] 2022/01/20 - 22:10:21 | 200 |    2.411214ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/soil_temperature
[GIN] 2022/01/21 - 02:10:08 | 201 |    1.055118ms |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/21 - 02:10:08 | 200 |     105.578µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/config?locale=en
[GIN] 2022/01/21 - 06:10:38 | 201 |      89.532µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/21 - 10:10:57 | 201 |      90.835µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/21 - 14:10:57 | 201 |      81.649µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/21 - 14:29:05 | 304 |    1.895198ms |      172.17.0.1 | GET      /
[GIN] 2022/01/21 - 14:29:05 | 304 |     105.762µs |      172.17.0.1 | GET      /js/Chart.bundle.min.js
[GIN] 2022/01/21 - 14:29:05 | 304 |     100.338µs |      172.17.0.1 | GET      /js/jquery.min.js
[GIN] 2022/01/21 - 14:29:06 | 200 |   15.718376ms |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/21 - 14:29:06 | 200 |    1.074188ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/soil_moisture
[GIN] 2022/01/21 - 14:29:06 | 200 |     916.578µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/battery_voltage
[GIN] 2022/01/21 - 14:29:06 | 200 |    1.147912ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/light
[GIN] 2022/01/21 - 14:29:06 | 200 |    1.821573ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/temperature
[GIN] 2022/01/21 - 14:29:06 | 200 |    2.272332ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/rssi
[GIN] 2022/01/21 - 14:29:06 | 200 |      324.03µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/soil_temperature
[GIN] 2022/01/21 - 14:47:04 | 200 |     235.661µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/21 - 14:47:04 | 200 |     642.505µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/soil_moisture
[GIN] 2022/01/21 - 14:47:04 | 200 |     421.335µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/rssi
[GIN] 2022/01/21 - 14:47:04 | 200 |    1.014069ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/battery_voltage
[GIN] 2022/01/21 - 14:47:04 | 200 |     389.631µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/temperature
[GIN] 2022/01/21 - 14:47:04 | 200 |     390.579µs |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/soil_temperature
[GIN] 2022/01/21 - 14:47:04 | 200 |     1.47007ms |      172.17.0.1 | GET      /v1/smart_devices/000666806f61/light
[GIN] 2022/01/21 - 18:11:15 | 201 |   13.583926ms |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/21 - 18:11:15 | 200 |     116.294µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/config?locale=en
[GIN] 2022/01/21 - 19:00:10 | 201 |    1.070681ms |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/21 - 19:00:37 | 304 |     340.037µs |      172.17.0.1 | GET      /
[GIN] 2022/01/21 - 19:00:37 | 304 |     1.01288ms |      172.17.0.1 | GET      /js/Chart.bundle.min.js
[GIN] 2022/01/21 - 19:00:37 | 304 |    1.384886ms |      172.17.0.1 | GET      /js/jquery.min.js
[GIN] 2022/01/21 - 19:00:37 | 200 |    12.93626ms |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/21 - 19:23:17 | 200 |   22.076212ms |      172.17.0.1 | GET      /
[GIN] 2022/01/21 - 19:23:17 | 200 |     201.037µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/21 - 23:00:30 | 201 |      108.68µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 03:00:51 | 201 |     105.743µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 07:01:08 | 201 |      71.478µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 11:00:58 | 201 |      98.643µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 15:01:04 | 201 |    1.276064ms |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 18:12:53 | 200 |    2.169478ms |      172.17.0.1 | GET      /
[GIN] 2022/01/22 - 18:12:53 | 304 |      79.475µs |      172.17.0.1 | GET      /js/jquery.min.js
[GIN] 2022/01/22 - 18:12:53 | 304 |     127.813µs |      172.17.0.1 | GET      /js/Chart.bundle.min.js
[GIN] 2022/01/22 - 18:12:53 | 200 |    4.243949ms |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 18:13:05 | 200 |     120.859µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 18:13:08 | 200 |      101.87µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 18:13:36 | 200 |     107.588µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 18:13:37 | 200 |     133.753µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 19:01:28 | 201 |      68.147µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 22:03:09 | 200 |     215.995µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 22:56:01 | 304 |     149.532µs |      172.17.0.1 | GET      /js/Chart.bundle.min.js
[GIN] 2022/01/22 - 22:56:01 | 304 |      81.585µs |      172.17.0.1 | GET      /js/jquery.min.js
[GIN] 2022/01/22 - 22:56:01 | 304 |      42.349µs |      172.17.0.1 | GET      /js/jquery.min.js
[GIN] 2022/01/22 - 22:56:01 | 200 |     128.181µs |      172.17.0.1 | GET      /v1/smart_devices
[GIN] 2022/01/22 - 23:01:52 | 201 |     130.048µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/22 - 23:01:52 | 200 |     494.689µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/config?locale=en
[GIN] 2022/01/23 - 03:02:15 | 201 |      65.661µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/23 - 07:02:33 | 201 |      60.678µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/23 - 11:02:24 | 201 |       86.49µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/23 - 15:02:33 | 201 |     114.934µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/23 - 19:03:00 | 201 |      98.651µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/23 - 23:03:36 | 201 |      82.111µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/24 - 03:04:02 | 201 |      67.131µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/24 - 07:04:23 | 201 |      65.845µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/24 - 11:04:25 | 201 |      93.232µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en
[GIN] 2022/01/24 - 15:03:25 | 201 |      75.583µs |      172.17.0.1 | POST     /v1/smart_devices/000666806f61/readings?locale=en

**Comment by polpas** [comment]
Would it be possible you send me a database without your personal koubachi data retrieved data?

I would by filling with my Mac address the data of your tables check if it would work.

My tables are not populated with sensors names I had to filled by hand

**Comment by munzli** [comment]
looks like you are receiving readings. is the database file writable by docker? restarting the container after removing the database file should create a new one. if there are no rows in the device and sensors tables they should be created automatically, manually entering data is not recommended.

the only other option that i can recommend is debugging the code locally to find the root cause.

**Comment by polpas** [comment]
Please send me a pm

My email is

Franciscoamartinsathotmaildotcom

Enviado do meu iPhone

**Comment by polpas** [comment]
I have bought another koubachi and it populates the values in database without issues. My 1st device is broken.
