### ISSUE TITLE
When docker is build it create repo

### ISSUE THREAD

**Issue by polpas** [munzli/koubachi-goserver#3]
When docker is built it create 2 repos one of 14 Mb and one of 550 Mb is this ok?

When I list doker images I get 1 unknown docker image of 550 Mb with name none. shouldnt the docker build create one image only?

**Comment by munzli** [comment]
if you look at the Dockerfile you will see that it is a multi-stage build.
using `golang:1.15-alpine` as the builder image and `alpine:latest` as the runner that contains the executable.
